import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  tabs: { flexDirection: "row", padding: 4, borderRadius: 14, backgroundColor: "#edf4f0" },
  tab: { flex: 1, alignItems: "center", justifyContent: "center", minHeight: 48, padding: 10, borderRadius: 10 },
  tabSelected: { backgroundColor: "#087454" },
  tabText: { color: "#536861", fontSize: 16, fontWeight: "600" },
  tabTextSelected: { color: "#ffffff" },
  page: { flex: 1, backgroundColor: "#ffffff" },
  content: {
    flexGrow: 1,
    justifyContent: "center",
    padding: 28,
    gap: 20,
    maxWidth: 520,
    width: "100%",
    alignSelf: "center",
  },
  logo: { fontSize: 42, fontWeight: "800", color: "#087454" },
  eyebrow: {
    color: "#087454",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 2,
  },
  title: { fontSize: 30, fontWeight: "700", color: "#173b33" },
  text: { fontSize: 16, lineHeight: 24, color: "#536861" },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 24,
    gap: 16,
    borderWidth: 1,
    borderColor: "#dbe7df",
  },
  label: { fontSize: 15, color: "#173b33", fontWeight: "600" },
  input: {
    borderWidth: 1,
    borderColor: "#b8cbc0",
    borderRadius: 12,
    padding: 15,
    fontSize: 16,
    color: "#173b33",
    backgroundColor: "#fbfdfb",
    minHeight: 52,
  },
  button: {
    backgroundColor: "#087454",
    padding: 17,
    borderRadius: 14,
    alignItems: "center",
    minHeight: 54,
  },
  buttonText: { fontSize: 16, fontWeight: "700", color: "#ffffff" },
  disabled: { opacity: 0.55 },
  error: { color: "#a32d29", fontSize: 14, lineHeight: 21 },
  link: {
    color: "#087454",
    fontSize: 14,
    fontWeight: "600",
    paddingVertical: 8,
  },
});
