import { StyleSheet } from "react-native";
import { colors, radius } from "./theme";

export const styles = StyleSheet.create({
  tabs: { flexDirection: "row", padding: 4, borderRadius: radius.md, backgroundColor: colors.mint },
  tab: { flex: 1, alignItems: "center", justifyContent: "center", minHeight: 46, padding: 10, borderRadius: radius.sm },
  tabSelected: { backgroundColor: colors.brand },
  tabText: { color: colors.muted, fontSize: 16, fontWeight: "600" },
  tabTextSelected: { color: colors.onBrand },
  page: { flex: 1, backgroundColor: colors.page },
  content: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
    gap: 16,
    maxWidth: 560,
    width: "100%",
    alignSelf: "center",
  },
  // Bandeau des écrans racines : vert profond, coins bas arrondis.
  hero: {
    backgroundColor: colors.brandDeep,
    borderBottomLeftRadius: radius.xl,
    borderBottomRightRadius: radius.xl,
    overflow: "hidden",
  },
  heroHalo: {
    position: "absolute",
    width: 240,
    height: 240,
    borderRadius: 120,
    right: -70,
    top: -110,
    backgroundColor: colors.brandBright,
    opacity: 0.16,
  },
  heroInner: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 48,
    gap: 4,
    maxWidth: 560,
    width: "100%",
    alignSelf: "center",
  },
  heroEyebrow: { color: colors.onBrandMuted, fontSize: 12, fontWeight: "700", letterSpacing: 1.6 },
  heroTitle: { color: colors.onBrand, fontSize: 28, fontWeight: "800" },
  heroSubtitle: { color: colors.onBrandMuted, fontSize: 15, lineHeight: 21 },
  // Barre des écrans secondaires : flèche retour + titre.
  // Barre fixe des écrans racine connectés : marque + déconnexion.
  accountBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 6,
    backgroundColor: colors.brandDeep,
  },
  accountBarBrand: { color: colors.onBrandMuted, fontSize: 15, fontWeight: "800", letterSpacing: 0.4 },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: colors.page,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: { width: 44, height: 44, borderRadius: 22, alignItems: "center", justifyContent: "center" },
  topBarTitle: { flex: 1, fontSize: 18, fontWeight: "700", color: colors.ink },
  logo: { fontSize: 42, fontWeight: "800", color: colors.brand },
  eyebrow: {
    color: colors.brand,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.6,
  },
  title: { fontSize: 28, fontWeight: "800", color: colors.ink },
  text: { fontSize: 15, lineHeight: 22, color: colors.muted },
  card: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: 20,
    gap: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  label: { fontSize: 15, color: colors.ink, fontWeight: "600" },
  input: {
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    padding: 14,
    fontSize: 16,
    color: colors.ink,
    backgroundColor: colors.mintSoft,
    minHeight: 50,
  },
  inputDisabled: { backgroundColor: colors.page, color: colors.muted, borderColor: colors.border },
  button: {
    flexDirection: "row",
    gap: 8,
    backgroundColor: colors.brand,
    paddingVertical: 15,
    paddingHorizontal: 18,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 52,
  },
  buttonSecondary: { backgroundColor: colors.mint },
  buttonGhost: { backgroundColor: "transparent", borderWidth: 1, borderColor: colors.borderStrong },
  buttonDanger: { backgroundColor: "#fbecea" },
  buttonText: { fontSize: 16, fontWeight: "700", color: colors.onBrand },
  disabled: { opacity: 0.55 },
  error: { color: colors.danger, fontSize: 14, lineHeight: 21 },
  link: {
    color: colors.brand,
    fontSize: 14,
    fontWeight: "700",
    paddingVertical: 8,
  },
  sectionHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  cardTitle: { fontSize: 18, fontWeight: "700", color: colors.ink },
  statusCard: {
    borderRadius: radius.lg,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  statusSymbol: {
    fontSize: 26,
    fontWeight: "800",
    width: 40,
    textAlign: "center",
  },
  statusLabel: { fontSize: 18, fontWeight: "800", marginTop: 2 },
  metricsRow: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  metric: {
    flexGrow: 1,
    flexBasis: 0,
    minWidth: 90,
    backgroundColor: colors.mintSoft,
    borderRadius: radius.md,
    padding: 12,
    gap: 4,
  },
  metricLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  metricValue: { color: colors.ink, fontSize: 20, fontWeight: "800" },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  historyItem: {
    borderTopWidth: 1,
    borderTopColor: "#e8efea",
    paddingTop: 12,
    gap: 4,
  },
  historyMain: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  historyWeight: { color: colors.ink, fontSize: 17, fontWeight: "700" },
  historyMeta: { color: colors.muted, fontSize: 13 },
  choiceRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  choice: {
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    paddingHorizontal: 14,
    paddingVertical: 11,
    backgroundColor: colors.mintSoft,
  },
  choiceSelected: { backgroundColor: colors.mint, borderColor: colors.brand },
  success: { color: colors.brand, fontSize: 14, lineHeight: 21, fontWeight: "600" },
  pill: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: colors.mint,
  },
  pillText: { color: colors.brand, fontSize: 12, fontWeight: "700" },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: colors.brand,
    borderRadius: 999,
    paddingHorizontal: 20,
    paddingVertical: 15,
    shadowColor: colors.brandDeep,
    shadowOpacity: 0.28,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
});
